<?php

/**
 * @file
 * Provides module logic for Library Tools module.
 */

// Include required files.
include_once 'librarytools.features.inc';
include_once "librarytools.admin.inc";
include_once "librarytools.library.inc";
include_once "librarytools.libraries.inc";
include_once "librarytools.theme.inc";

// Define constants.
define('LIBRARYTOOLS_LIBRARIES_OVERVIEW', 'admin/structure/libraries');
define('LIBRARYTOOLS_LIBRARIES_OVERVIEW_TAB', 'admin/structure/libraries/overview ');
define('LIBRARYTOOLS_LIBRARY_EXPORT_TAB', 'admin/structure/libraries/export');
define('LIBRARYTOOLS_LIBRARY_INFO', 'admin/structure/libraries/%librarytools_library_info/info');

/**
 * Callback for admin/structure/libraries menu hook.
 */
function librarytools_libraries_summary() {
  $output = '';

  if (module_exists('libraries')) {
    $output .= '<h2>' . t('Available <code>hook_libraries_info()</code> libraries') . '</h2>';
    $output .= _librarytools_hook_libraries_info_libraries();
  }
  $output .= '<h2>' . t('Available <code>hook_library()</code> libraries') . '</h2>';
  $output .= _librarytools_hook_library_libraries();

  return $output;
}

/**
 * Callback for admin/structure/libraries/%/info menu hook.
 */
function librarytools_library_info($library) {
  // Page title.
  reset($library);
  $library_name = key($library);
  drupal_set_title(t('Library info: @library_name', array('@library_name' => $library_name)));

  // Content.
  $content = !empty($library) ? kpr($library, TRUE) : t('No library name "@library" could be found.');

  return $content;
}

/**
 * Autoloader function for librarytools_library_info() function.
 */
function librarytools_library_info_load($library_name) {
  // Sanitize the input.
  $safe_library_name = check_plain($library_name);

  // (Attempt to) explode the input.
  $library_meta = explode(':', $safe_library_name);
  $argument_count = count($library_meta);

  // Attempt to load library by number of args and module existence.
  if ($argument_count > 1) {
    $library = drupal_get_library($library_meta[0], $library_meta[1]);
    $library_name = $library['title'];
  }
  elseif (module_exists('libraries') && $argument_count == 1) {
    $library = libraries_load($library_meta[0]);
    $library_name = $library['name'];
  }

  return isset($library) ? array($library_name => $library) : FALSE;
}

/**
 * Implements hook_menu().
 */
function librarytools_menu() {
  $items = array();

  // Library information page.
  $items[LIBRARYTOOLS_LIBRARIES_OVERVIEW] = array(
    'access arguments' => array('administer librarytools'),
    'description' => 'The libraries in the following table are available for use on this site',
    'page callback' => 'librarytools_libraries_summary',
    'title' => 'Library Tools',
    'type' => MENU_NORMAL_ITEM,
  );

  // Default tab.
  $items[LIBRARYTOOLS_LIBRARIES_OVERVIEW_TAB] = array(
    'title' => 'Available Libraries',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  $items[LIBRARYTOOLS_LIBRARY_EXPORT_TAB] = array(
    'access arguments' => array('administer librarytools'),
    'page arguments' => array('librarytools_library_export'),
    'page callback' => 'drupal_get_form',
    'title' => 'Library Export',
    'type' => MENU_LOCAL_TASK,
  );

  // Individual library information pages.
  $items[LIBRARYTOOLS_LIBRARY_INFO] = array(
    'access arguments' => array('administer librarytools'),
    'page arguments' => array(3),
    'page callback' => 'librarytools_library_info',
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements template_preprocess_field().
 */
function librarytools_preprocess_field(&$variables) {
  switch ($variables['element']['#bundle']) {
    case 'librarytools_core_library':
      if ($variables['element']['#field_type'] === 'text_long') {
        $variables['theme_hook_suggestions'][] = 'field__librarytools__text_long';
      }
      break;
  }
}

/**
 * Implements template_preprocess_page().
 */
function librarytools_preprocess_page(&$variables) {
  if (strpos('admin/structure/libraries', drupal_get_path_alias()) === 0) {
    drupal_add_css(drupal_get_path('module', 'librarytools') . '/css/librarytools.admin.css');
  }
}

/**
 * Implmenents hook_theme().
 */
function librarytools_theme() {
  $path_to_module = drupal_get_path('module', 'librarytools') . '/templates';

  $items = array(
    'librarytools_dependencies' => array(
      'variables' => array(
        'dependencies',
      ),
    ),
    'librarytools_dependency' => array(
      'variables' => array(
        'dependency_name' => NULL,
        'class_name' => NULL,
        'status' => NULL,
      ),
    ),
    'librarytools_title' => array(
      'variables' => array(
        'title' => NULL,
      ),
    ),
    // Entity.
    'librarytools_core_library' => array(
      'variables' => array(
        array(
          'element' => NULL,
        ),
      ),
      'template' => 'librarytools--library',
      'path' => $path_to_module,
    ),
  );

  // Textarea fiels in entity.
  $field__librarytools__text_long = isset($existing['field']) ? $existing['field'] : array();
  $field__librarytools__text_long['path'] = $path_to_module;
  $field__librarytools__text_long['template'] = 'field--librarytools--text-long';

  $items['field__librarytools__text_long'] = $field__librarytools__text_long;

  return $items;
}
